# Setup
title:        Calculatrice de distributions
tagline:      Une calculatrice dynamique pour vos problèmes de statistique et de probabilité
baseurl:      "https://alec42.github.io/distributacalcul/"
paginate:     1
locale:       "fr"

# About/contact
author:
  name:       Alec James van Rassel et Marc-André Devost
  url:        "https://alec42.shinyapps.io/distributacalcul/"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
