# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "https://alec42.github.io/distributacalcul/"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Alec James van Rassel et Marc-André Devost
  url:        https://alec42.github.io/distributacalcul/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: jekyll-theme-cayman
